# Generated by Django 5.0.6 on 2024-07-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Cash', 'Cash')], default='Credit Card', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='quanity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
